# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d916c2d32665beccf5638fd7dc8af4ddb1764dae775f7e72d5abd2e26ff11128a15685eea1ab150cded5cd875a4fe4e231e292ef858923755a849fa0a32f073

test:
  secret_key_base: bdf8fcfcc5a6c2c78bb1209934e82e24afcb149e4a7dc896a2e665cae6ff0ad7373b8a3aada37cf17da3636d50f791cb3ee5d06932b08e9282b58ce72cea36b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
